apiVersion: v1
kind: Service
metadata:
  labels:
    job: node-api
    app: a-service
  name: a-service
spec:
  type: ClusterIP       # Changed from LoadBalancer
  selector:
    app: service-a-deployment
  ports:
    - name: a-service-port
      port: 80
      protocol: TCP
      targetPort: 3001
